name: Build and publish to NPM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        registry-url: 'https://registry.npmjs.org'

    - run: yarn
    - run: yarn run build
    - run: yarn npm publish
      env:
        YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
