name: Build and publish to NPM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Transpile to JS
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run build

    - name: Publish
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
